export const BOOKING_ROUTE_URL = "/desks/booking"
export const CHECKIN_DESKPREFIX_ROUTE_URL = "/desks/checkin/?b2."
export const CHECKIN_ROUTE_URL = "/desks/checkin/"
export const USER_ROUTE_URL = "/desks/user"
export const LOGIN_ROUTE_URL = "/desks/login"
export const REGISTER_ROUTE_URL = "/desks/register"
export const ADMIN_ROUTE_URL = "/desks/admin"
